fix : Images not updated if registry or repository is different with same version
argoproj-labs/argocd-image-updater pull request #194
Opened 2021-04-14 22:31 UTC by iamnoah

Given this config:
```
imageList: foo=bar:>=1.0.0
foo.kustomize.image-name=gcr.io/bar
```

If my application is running `bar:1.0.0` I'd expect an update to `gcr.io/bar:1.0.0`, however that was not happening because only tag was considered in the difference. To fix that, I had to add an extra "KustomizeImage" to also be considered for matching purposes, and add registry and name to the update check if this kustomize image is present.

I've added an additional test to show that once updated there should be no more updates (no endless loop of updates, etc.)

This is builds off of #192

2021-04-18 15:31 UTC, jannfis reviewed
Thanks for your PR @iamnoah and sorry, but I'm having a hard time understanding the reasoning behind it.

The `<alias>.kustomize.image-name` is currently used to define which Kustomize image to override. With this change, the value of that annotation would be included to be checked for new versions, despite we want to check for updates to the overriden image? Why would we also want to check for the original image here?

Again sorry for not understanding it, but could you maybe elaborate a little on the use case?

2021-04-19 00:51 UTC, iamnoah commented
> could you maybe elaborate a little on the use case?

Sure. The issue is having a existing deployment like this:

```yaml
spec:
  template:
   spec:
    containers:
      - image: bar:latest
```

If I wasn't using image updater, I would add a kustomization like this:

```yaml
kind: Kustomization
images:
- name: bar
  newName: gcr.io/bar
  newTag: 0.1.0
```

That would update the image to `gcr.io/bar:0.1.0`.

But `.argocd-source.yaml` will override anything I put in `images` with this:

```yaml
images:
- bar:0.1.0
```

When what I wanted was:

```yaml
images:
- bar=gcr.io/bar:0.1.0
```

So I am forced to tell image updater about the re-mapping via `kustomize-name`.


Why does this happen? Because when looking at a deployed app, image updater will check `applicationImages.ContainsImage(applicationImage, false)`. There is no match because `gcr.io/bar` isn't `bar`. 

So we need a different `ContainerImage` to check.  What if we just look for `bar` instead, since that is what `kustomize-name` says to do?
- If the application doesn't have an override yet, we will find `bar` and override it with `gcr.io/bar` as long as the tag is different. If they are the same tag, nothing happens.
- If the image *is* overriden then looking for `bar` won't work because now the application contains only `gcr.io/bar`!

The problem is that the current state of application images can't tell you anything about what was overriden, and if we do fix the match, but have the same tags, no update happens. So we need two fixes:
- Match either `kustomize-name` or the override name to handle both the case where the image has not been update and the one where it has.
- If a `kustomize-name` is present, check if the desired registry is correct.

2021-04-19 00:55 UTC, iamnoah commented on pkg/argocd/argocd.go
> +func parseImageList(annotations map[string]string) *image.ContainerImageList {
I am fine with that, but I think I have demonstrated here that for non-trivial kustomize use cases, more config than just the image list is necessary, so some complex object or multiple parameters will have to be passed in.

2021-04-22 06:20 UTC, jannfis requested changes
Thanks for your thorough explanation @iamnoah and sorry that it took me a little longer to review, it was a busy week so far.

I have a couple of change requests, please see below.

2021-04-22 06:20 UTC, jannfis commented on pkg/argocd/argocd.go
> +			if kustomizeImage, ok := annotations[fmt.Sprintf(common.KustomizeApplicationNameAnnotation, img.ImageAlias)]; ok {
Can you please use `image.GetParameterKustomizeImageName()` instead of going through annotations manually, please?

2021-04-22 06:20 UTC, jannfis commented on pkg/argocd/argocd.go
> +		if forceStr, force := annotations[fmt.Sprintf(common.ForceUpdateOptionAnnotation, img.ImageAlias)]; force && strings.ToLower(forceStr) == "true" {
We do not have an `image.HasForceUpdateOptionAnnotation()` method yet, but maybe we should introduce one for this purpose?

2021-04-26 12:43 UTC, jannfis approved these changes
LGTM now!

Thank you for your contribution and your patience, @iamnoah!

2021-04-26 12:43 UTC, merged