use HTTP_PROXY for registry endpoint
argoproj-labs/argocd-image-updater pull request #300
Opened 2021-11-17 12:31 UTC by derdanne

use HTTP_PROXY in transport object for registry endpoint if defined in environment

2021-11-17 12:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj-labs/argocd-image-updater?pullRequest=300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj-labs/argocd-image-updater?pullRequest=300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj-labs/argocd-image-updater?pullRequest=300) it.</sub>

2021-11-18 12:34 UTC, jannfis requested changes
Thanks a lot for your contribution, @derdanne !

I think it would be easier to use `http.ProxyFromEnvironment` method for setting the `Transport`'s proxy configuration, instead of rolling up our own logic for getting the environment. This would also have the benefit that `https_proxy` and `no_proxy` would be considered as well.

Reference can be found at: https://pkg.go.dev/net/http#ProxyFromEnvironment

2022-01-08 15:34 UTC, derdanne commented
Hey thanks for the feedback. I have switched to the http.ProxyFromEnvironment method.

2022-01-09 19:24 UTC, jannfis approved these changes
LGTM! Thank you for this contribution, @derdanne !

2022-01-09 19:24 UTC, merged