Respect original override parameters with git write-back
argoproj-labs/argocd-image-updater pull request #573
Opened 2023-06-09 09:43 UTC by ks-yim

Modification:

Make image-updater respect the original parameter overrides written in `.argocd-source-<appName>.yaml`.

Motivation:

Currently, the original overridden parameters stored in `.argocd-source-<appName>.yaml`
are not respected when image-updater writes back its change to git.

Imagine that a user has originally defined `.argocd-source-<appName>.yaml` like below
```yaml
helm
    parameters:
    - name: some.prop
      value: some-value
```
...and image-updater wants to write back additional overrides below
- `foo.image.repository: foo`
- `foo.image.tag: 2.0.0`

The user may want the edited file to be like...
```yaml
helm
    parameters:
    - name: some.prop
      value: some-value
      focestring: true
    - name: foo.image.repository
      value: foo
      forcestring: true
    - name: foo.image.tag
      value: 2.0.0
      forcestring: true
```
... but what's actually committed to git is the following and it deletes the user-defined parameter overrides.
```yaml
helm:
    parameters:
    - name: foo.image.repository
      value: foo
      forcestring: true
    - name: foo.image.tag
      value: 2.0.0
      forcestring: true
```

And this image-updater behavior is a suspected cause of #562 and the likes
as image-updater ignores the tags for an image that it failed to fetch when
there are multiple updatable images defined in an `Application` and generate 
the parameter overrides without the ignored image. 
If only a part of image tags were successfully fetched from the image registry
due to unstable network, image-updater may write a broken parameter override
file to git.

2023-07-06 01:46 UTC, jannfis requested changes
Nice one, thank you!

The linter complained, and it turns out your code shadows `err` in one place. Please fix it, otherwise LGTM :)

2023-07-06 01:46 UTC, jannfis commented on pkg/argocd/update.go
> +		err := yaml.Unmarshal(originalData, &params)
```suggestion
		err = yaml.Unmarshal(originalData, &params)
```

2023-07-06 01:47 UTC, jannfis commented
Oh, and please make sure the DCO passes by signing off your commits

2023-07-09 05:21 UTC, ks-yim commented
@jannfis
Thanks for taking your time to review this!

The issue described in the PR description has actually caused a disruption to our production(insignificant, though) workload so it would be very nice if this PR is shipped into the next release.

Resolved the variable shadowing issue and signed-off all my commits included in the PR.
I tried to make it pass `Spell checking` and `Run codegen` by merging the latest `master` but had no luck. 😅

2023-07-09 21:29 UTC, jannfis commented
Thanks for looking into it, @ks-yim!

I have just merged #590 , so if you rebase your PR, the codegen step should pass.

I'm aiming to release v0.13.0 after https://github.com/argoproj-labs/argocd-image-updater/pull/578 has been merged, however, it needs some attention from the submitter.

2023-07-09 21:33 UTC, jannfis approved these changes
LGTM. Going to merge it without rebase required, because the codegen error is negligible.

2023-07-09 21:34 UTC, merged